name: Three.js World
description: The place fo three.js tutorials and showcases
url: http://www.threejsworld.com
timezone: America/Los_Angeles
repository: martyboggs/threejs-world
permalink: /:categories/:title
