title: Three.js World
description: The place fo three.js tutorials and showcases
three_version: r83
timezone: America/Los_Angeles
repository: martyboggs/threejs-world
permalink: /:categories/:title
excerpt_separator: <!--more-->
collections:
  categories:
    permalink: /category/:name
    output: true
  tags:
    permalink: /tag/:name
    output: true
  archive_collection:
    permalink: /all/:name
    output: true
  models:
    output: true
