title: Three.js World
description: The place fo three.js tutorials and showcases
three_version: 84
timezone: America/Los_Angeles
repository: martyboggs/threejs-world
permalink: /:categories/:title
excerpt_separator: <!--more-->
# incremental: true
exclude:
-  notes.txt
-  study.txt
-  pablo.js
collections:
  archive_category:
    permalink: /category/:name
    output: true
  archive_tag:
    permalink: /tag/:name
    output: true
  archive_collection:
    permalink: /all/:name
    output: true
  models:
    output: true
