title: Three.js World
description: The place fo three.js tutorials and showcases
three_version: 85
timezone: America/Los_Angeles
repository: martyboggs/threejs-world
permalink: /:categories/:title
host: 0.0.0.0
port: 3000
excerpt_separator: <!--more-->
# incremental: true
gems:
- jekyll-redirect-from
exclude:
-  notes.txt
-  study.txt
-  pablo.js
-  gifs
collections:
  archive_category:
    permalink: /category/:name
    output: true
  archive_tag:
    permalink: /tag/:name
    output: true
  archive_collection:
    permalink: /all/:name
    output: true
  models:
    output: true
